<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TTMCHybrid" nsURI="http://www.inf.mit.bme.hu/ttmc/TTMCHybrid"
    nsPrefix="TTMCHybrid">
  <eClassifiers xsi:type="ecore:EClass" name="HybridSpecification" eSuperTypes="../../hu.bme.mit.inf.ttmc.constraint.model/model/TTMCConstraint.ecore#//ConstraintSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hybridAutomatonDeclarations"
        upperBound="-1" eType="#//HybridAutomatonDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyDeclarations" upperBound="-1"
        eType="#//PropertyDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClockTypeDefinition" eSuperTypes="../../hu.bme.mit.inf.ttmc.constraint.model/model/TTMCConstraint.ecore#//BasicTypeDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="DotExpression" eSuperTypes="../../hu.bme.mit.inf.ttmc.constraint.model/model/TTMCConstraint.ecore#//UnaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="LocationReferenceExpression" eSuperTypes="../../hu.bme.mit.inf.ttmc.constraint.model/model/TTMCConstraint.ecore#//NullaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//Location"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HybridAutomaton" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="HybridAutomatonDeclaration" eSuperTypes="../../hu.bme.mit.inf.ttmc.constraint.model/model/TTMCConstraint.ecore#//NamedElement ../../hu.bme.mit.inf.ttmc.constraint.model/model/TTMCConstraint.ecore#//ParametricElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hybridAutomaton" lowerBound="1"
        eType="#//HybridAutomaton" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HybridAutomatonReference" eSuperTypes="#//HybridAutomaton ../../hu.bme.mit.inf.ttmc.constraint.model/model/TTMCConstraint.ecore#//ParametrizedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" lowerBound="1"
        eType="#//HybridAutomatonDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HybridAutomatonDefinition" eSuperTypes="#//HybridAutomaton">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableDeclarations" upperBound="-1"
        eType="#//VariableDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="locations" upperBound="-1"
        eType="#//Location" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" abstract="true"
      eSuperTypes="../../hu.bme.mit.inf.ttmc.constraint.model/model/TTMCConstraint.ecore#//Declaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="LocalVariableDeclaration" eSuperTypes="#//VariableDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalVariableDeclaration" eSuperTypes="#//VariableDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="Location" eSuperTypes="../../hu.bme.mit.inf.ttmc.constraint.model/model/TTMCConstraint.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" upperBound="-1"
        eType="#//Condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.inf.ttmc.constraint.model/model/TTMCConstraint.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialCondition" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="InvariantCondition" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlowCondition" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="../../hu.bme.mit.inf.ttmc.constraint.model/model/TTMCConstraint.ecore#//ParametricElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guards" upperBound="-1"
        eType="ecore:EClass ../../hu.bme.mit.inf.ttmc.constraint.model/model/TTMCConstraint.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" upperBound="-1"
        eType="#//Assignment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.inf.ttmc.constraint.model/model/TTMCConstraint.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="ecore:EClass ../../hu.bme.mit.inf.ttmc.constraint.model/model/TTMCConstraint.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyDeclaration" eSuperTypes="../../hu.bme.mit.inf.ttmc.constraint.model/model/TTMCConstraint.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hybridAutomaton" lowerBound="1"
        eType="#//HybridAutomaton" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="ecore:EClass ../../hu.bme.mit.inf.ttmc.constraint.model/model/TTMCConstraint.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
