/*
 * generated by Xtext
 */
package hu.bme.mit.inf.ttmc.hybrid.language.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import hu.bme.mit.inf.ttmc.hybrid.language.ui.internal.TTMCHybridLanguageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TTMCHybridLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TTMCHybridLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TTMCHybridLanguageActivator.getInstance().getInjector(TTMCHybridLanguageActivator.HU_BME_MIT_INF_TTMC_HYBRID_LANGUAGE_TTMCHYBRIDLANGUAGE);
	}
	
}
