/*
 * generated by Xtext
 */
package hu.bme.mit.inf.ttmc.hybrid.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TTMCHybridLanguageUiModule extends hu.bme.mit.inf.ttmc.hybrid.language.ui.AbstractTTMCHybridLanguageUiModule {
	public TTMCHybridLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
