/*
 * generated by Xtext
 */
package hu.bme.mit.inf.ttmc.constraint.language.ui.contentassist

import hu.bme.mit.inf.ttmc.constraint.language.ui.contentassist.AbstractTTMCConstraintLanguageProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class TTMCConstraintLanguageProposalProvider extends AbstractTTMCConstraintLanguageProposalProvider {
}
