/*
 * generated by Xtext
 */
package hu.bme.mit.inf.ttmc.constraint.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TTMCConstraintLanguageUiModule extends hu.bme.mit.inf.ttmc.constraint.language.ui.AbstractTTMCConstraintLanguageUiModule {
	public TTMCConstraintLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
