/*
 * generated by Xtext
 */
package hu.bme.mit.inf.ttmc.hybrid.language.ui.contentassist

import hu.bme.mit.inf.ttmc.hybrid.language.ui.contentassist.AbstractTTMCHybridLanguageProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class TTMCHybridLanguageProposalProvider extends AbstractTTMCHybridLanguageProposalProvider {
}
