/*
* generated by Xtext
*/
package hu.bme.mit.inf.ttmc.system.language;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TTMCSystemLanguageStandaloneSetup extends TTMCSystemLanguageStandaloneSetupGenerated{

	public static void doSetup() {
		new TTMCSystemLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

