/*
 * generated by Xtext
 */
package hu.bme.mit.inf.ttmc.system.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TTMCSystemLanguageRuntimeModule extends hu.bme.mit.inf.ttmc.system.language.AbstractTTMCSystemLanguageRuntimeModule {

}
