/*
 * generated by Xtext
 */
package hu.bme.mit.inf.ttmc.system.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TTMCSystemLanguageUiModule extends hu.bme.mit.inf.ttmc.system.language.ui.AbstractTTMCSystemLanguageUiModule {
	public TTMCSystemLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
