/*
 * generated by Xtext
 */
package hu.bme.mit.inf.ttmc.system.language.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import hu.bme.mit.inf.ttmc.system.language.services.TTMCSystemLanguageGrammarAccess;

public class TTMCSystemLanguageParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TTMCSystemLanguageGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected hu.bme.mit.inf.ttmc.system.language.parser.antlr.internal.InternalTTMCSystemLanguageParser createParser(XtextTokenStream stream) {
		return new hu.bme.mit.inf.ttmc.system.language.parser.antlr.internal.InternalTTMCSystemLanguageParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "SystemSpecification";
	}
	
	public TTMCSystemLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TTMCSystemLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
