/*
 * generated by Xtext
 */
package hu.bme.mit.inf.ttmc.constraint.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TTMCConstraintLanguageRuntimeModule extends hu.bme.mit.inf.ttmc.constraint.language.AbstractTTMCConstraintLanguageRuntimeModule {	
}
