/*
* generated by Xtext
*/
package hu.bme.mit.inf.ttmc.constraint.language;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TTMCConstraintLanguageStandaloneSetup extends TTMCConstraintLanguageStandaloneSetupGenerated{

	public static void doSetup() {
		new TTMCConstraintLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

