/*
 * generated by Xtext
 */
package hu.bme.mit.inf.ttmc.constraint.language.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import hu.bme.mit.inf.ttmc.constraint.language.services.TTMCConstraintLanguageGrammarAccess;

public class TTMCConstraintLanguageParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TTMCConstraintLanguageGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected hu.bme.mit.inf.ttmc.constraint.language.parser.antlr.internal.InternalTTMCConstraintLanguageParser createParser(XtextTokenStream stream) {
		return new hu.bme.mit.inf.ttmc.constraint.language.parser.antlr.internal.InternalTTMCConstraintLanguageParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ConstraintSpecification";
	}
	
	public TTMCConstraintLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TTMCConstraintLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
