/*
 * generated by Xtext
 */
package hu.bme.mit.inf.ttmc.system.language.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import hu.bme.mit.inf.ttmc.system.language.ui.internal.TTMCSystemLanguageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TTMCSystemLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TTMCSystemLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TTMCSystemLanguageActivator.getInstance().getInjector(TTMCSystemLanguageActivator.HU_BME_MIT_INF_TTMC_SYSTEM_LANGUAGE_TTMCSYSTEMLANGUAGE);
	}
	
}
