/**
 *
 * $Id$
 */
package TTMCHybrid.validation;

import TTMCConstraint.Expression;

/**
 * A sample validator interface for {@link TTMCHybrid.Assignment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AssignmentValidator {
	boolean validate();

	boolean validateLhs(Expression value);
	boolean validateRhs(Expression value);
}
