/**
 *
 * $Id$
 */
package TTMCHybrid.validation;

import TTMCHybrid.HybridAutomatonDeclaration;
import TTMCHybrid.PropertyDeclaration;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link TTMCHybrid.HybridSpecification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HybridSpecificationValidator {
	boolean validate();

	boolean validateHybridAutomatonDeclarations(EList<HybridAutomatonDeclaration> value);
	boolean validatePropertyDeclarations(EList<PropertyDeclaration> value);
}
