/**
 *
 * $Id$
 */
package TTMCHybrid.validation;

import TTMCConstraint.Expression;

import TTMCHybrid.Assignment;
import TTMCHybrid.Location;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link TTMCHybrid.Transition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransitionValidator {
	boolean validate();

	boolean validateSource(Location value);
	boolean validateTarget(Location value);
	boolean validateGuards(EList<Expression> value);
	boolean validateAssignments(EList<Assignment> value);
}
