/*
 * generated by Xtext
 */
package hu.bme.mit.inf.ttmc.hybrid.language.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TTMCHybridLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("hu/bme/mit/inf/ttmc/hybrid/language/parser/antlr/internal/InternalTTMCHybridLanguage.tokens");
	}
}
