/**
 *
 * $Id$
 */
package TTMCConstraint.validation;

import TTMCConstraint.BasicConstraintDefinition;
import TTMCConstraint.ConstantDeclaration;
import TTMCConstraint.FunctionDeclaration;
import TTMCConstraint.TypeDeclaration;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link TTMCConstraint.ConstraintSpecification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConstraintSpecificationValidator {
	boolean validate();

	boolean validateTypeDeclarations(EList<TypeDeclaration> value);
	boolean validateConstantDeclarations(EList<ConstantDeclaration> value);
	boolean validateFunctionDeclarations(EList<FunctionDeclaration> value);
	boolean validateBasicConstraintDefinitions(EList<BasicConstraintDefinition> value);
}
