/*
 * generated by Xtext
 */
package hu.bme.mit.inf.ttmc.constraint.language.serializer

class TTMCConstraintLanguageSemanticSequencer extends AbstractTTMCConstraintLanguageSemanticSequencer {
}
