/*
 * generated by Xtext
 */
package hu.bme.mit.inf.ttmc.hybrid.language;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TTMCHybridLanguageStandaloneSetup extends TTMCHybridLanguageStandaloneSetupGenerated{

	public static void doSetup() {
		new TTMCHybridLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

